cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

default:
  image: node:latest

stages:
  - lint
  - test
  - deploy

deploy_preview:
  stage: deploy
  except:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN

integration_testing:
  image: cypress/base:latest
  stage: test
  script:
    - npm ci
    - npx vite dev --port 4173 &
    - npx cypress run --e2e

component_testing:
  stage: test
  script:
    - npm i
    - npm run test:unit

linting:
  stage: lint
  script:
    - npm i
    - npm run lint